/driver/lidar/lidar_front/imu/Data:
  reliability: reliable
  durability: volatile
  history: keep_last
  depth: 4000

/driver/lidar/point_cloud/Data:
  reliability: reliable
  durability: volatile
  history: keep_last
  depth: 500

/driver/lidar/lidar_front/point_cloud/Data:
  reliability: reliable
  durability: volatile
  history: keep_last
  depth: 500

/driver/lidar/lidar_back/point_cloud/Data:
  reliability: reliable
  durability: volatile
  history: keep_last
  depth: 500
